name: Test Build

on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
      
      - name: List build output
        run: ls -la dist/
      
      - name: Verify index.html
        run: |
          if [ -f "dist/index.html" ]; then
            echo "✅ index.html exists"
          else
            echo "❌ index.html is missing"
            exit 1
          fi
          
      - name: Verify JS files
        run: |
          if ls dist/assets/*.js 1> /dev/null 2>&1; then
            echo "✅ JS assets exist"
          else
            echo "❌ JS assets are missing"
            exit 1
          fi 